### ISSUE TITLE
Improve max capacity path calculations

### ISSUE THREAD

**Issue by cducrest** [trustlines-network/relay#211]
https://github.com/trustlines-network/mobileapp/issues/296

Improve calculations to make the result returned better.

**Comment by cducrest** [comment]
I'm waiting for all the shenanigans with the fees to be over before looking again at this issue, since changing the way we calculate the fees will require changing the estimation anyway.

**Comment by schmir** [comment]
I do think that this could be solved by running a binary search.

The `fix/adapt-to-contracts-0.4` relay server branch already contains the code to search for the best path.

Instead of estimating, you could run a binary search algorithm in order to find the maximum amount that can be transferred.

You can test if a transfer would succeed by instantiating a graph.SenderPaysCostAccumulatorSnapshot and call its `compute_cost_for_path` method, which will throw if the `value` cannot be transferred.

**Comment by cducrest** [comment]
Do you agree with using a poor low and high estimate and a binary search method to find the max sendable amount @berndbohmeier ? This will make the code easier to maintain if we come to change the fee model once again in the future.
